name: 1st time buyers
favicon: null
layout_spectrum: 0.9473907016217709
typography_spectrum: 0.4650235993321985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41972568118944764
  lightness: 0.7428284329362214
  saturation: 0.3109686926472932
  rhythmicContrast: 0.7926629667636007
purpose: []
